[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contracts = "4RmcfUfBuX78VABySpG7p5nzCAbqWLLJdbJ6DiYPZyFS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/emilemilovroydev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
